### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xdk78** [xdk78/Ekonom-mobile#1]
TODO:

- [x] Basic API
- [ ] Functional news feed
- [x] Basic Substitutions scrapping
- [ ] Better Substitutions scrapping
- [ ] More things from website
- [ ] Making app GOOD - better code
